In [18]:
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
df = pd.read_csv('/Users/swimmingcircle/Documents/CS156/fccmediumTitles_Cleaned_Data.tsv', on_bad_lines='skip', sep='\t')

In [14]:
df

,Quartier,date,Title,Recommends,Read ratio
0,4,October 2016,Upgrading to MacOS Sierra will break your SSH ...,58,48%
1,4,October 2016,How Crowd Curation Improved Our Search Quality...,28,37%
2,4,October 2016,Code Briefing: What I learned from reviewing 5...,56,59%
3,4,October 2016,What I learned from reviewing 50 portfolios on...,635,49%
4,4,October 2016,JavaScript Fatigue Fatigue In Free Code CampVi...,1100,55%
...,...,...,...,...,...
448,1,October 2015,Gulp! I Improved my Workflow! In Free Code Cam...,49,30%
449,1,October 2015,Beginners Guide to Big O Notation In Free Code...,108,54%
450,1,October 2015,7 Ways Streaming Makes you a Better Coder In F...,142,61%
451,1,October 2015,Jump Start Your Local Campsite with Coffee-and...,50,70%
452,1,October 2015,Commit to Yourself. Commit to a Nonprofit. In ...,23,80%

In [22]:
text_files = df['Title']

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(df['Title'])
x.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
import numpy as np

# df = pd.DataFrame({'docId': [1,2,3], 
#                'sent': ['This is the first sentence', 
#                         'This is the second sentence',
#                         'This is the third sentence']})

# Tokenize and generate count vectors
word_vec = df.Title.apply(str.split).apply(pd.value_counts).fillna(0)

# Compute term frequencies
tf = word_vec.divide(np.sum(word_vec, axis=1), axis=0)

# Compute inverse document frequencies
idf = np.log10(len(tf) / word_vec[word_vec > 0].count()) 

# Compute TF-IDF vectors
tfidf = np.multiply(tf, idf.to_frame().T)

print(tfidf)

        your  Upgrading       you  CampView  Code  Free   In  servers.  \
0    0.11283   0.120732  0.064802       0.0   0.0   0.0  0.0  0.120732
1    0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
2    0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
3    0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
4    0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
..       ...        ...       ...       ...   ...   ...  ...       ...
448  0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
449  0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
450  0.00000   0.000000  0.109665       0.0   0.0   0.0  0.0  0.000000
451  0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000
452  0.00000   0.000000  0.000000       0.0   0.0   0.0  0.0  0.000000

          own        of  ...  Beginners         O  Notation  Streaming  \
0    0.079682  0.041987  ...   0.000000  0.000000  0.000000   0.000000
1    0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
2    0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
3    0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
4    0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
..        ...       ...  ...        ...       ...       ...        ...
448  0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
449  0.000000  0.000000  ...   0.241463  0.241463  0.241463   0.000000
450  0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.204315
451  0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000
452  0.000000  0.000000  ...   0.000000  0.000000  0.000000   0.000000

        Coder      Jump     Local  Coffee-and-Code  Yourself.  Nonprofit.
0    0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
1    0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
2    0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
3    0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
4    0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
..        ...       ...       ...              ...        ...         ...
448  0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
449  0.000000  0.000000  0.000000         0.000000   0.000000    0.000000
450  0.204315  0.000000  0.000000         0.000000   0.000000    0.000000
451  0.000000  0.221342  0.221342         0.221342   0.000000    0.000000
452  0.000000  0.000000  0.000000         0.000000   0.221342    0.221342

[453 rows x 1676 columns]

/var/folders/0h/xyv81g2n7sj6zr0c9cw30gkc0000gn/T/ipykernel_15492/3308623683.py:18: FutureWarning: Calling a ufunc on non-aligned DataFrames (or DataFrame/Series combination). Currently, the indices are ignored and the result takes the index/columns of the first DataFrame. In the future , the DataFrames/Series will be aligned before applying the ufunc.
Convert one of the arguments to a NumPy array (eg 'ufunc(df1, np.asarray(df2)') to keep the current behaviour, or align manually (eg 'df1, df2 = df1.align(df2)') before passing to the ufunc to obtain the future behaviour and silence this warning.
  tfidf = np.multiply(tf, idf.to_frame().T)

In [50]:
tfidf.sum().sort_values(ascending=False)

to            4.980640
a             4.358611
and           4.103964
the           4.016245
How           3.672922
in            3.654337
of            3.627802
The           3.284766
JavaScript    3.147535
for           2.826977
I             2.692718
your          2.665147
with          2.653374
Building      2.468115
Best          2.449820
Android       2.156164
Gitter        2.086762
A             2.056568
on            1.893964
code          1.736890
dtype: float64

In [44]:
tfidf_words = tfidf.sum().to_frame(name="tf-idf")
tfidf_words

                   tf-idf
your             2.665147
Upgrading        0.120732
you              1.657016
CampView         0.000000
Code             0.000000
...                   ...
Jump             0.221342
Local            0.221342
Coffee-and-Code  0.221342
Yourself.        0.221342
Nonprofit.       0.221342

[1676 rows x 1 columns]

In [46]:
tfidf_words.rank()

                 tf-idf
your             1665.0
Upgrading          31.5
you              1655.0
CampView            3.0
Code                3.0
...                 ...
Jump              856.5
Local             856.5
Coffee-and-Code   856.5
Yourself.         856.5
Nonprofit.        856.5

[1676 rows x 1 columns]

In [ ]:
import en_core_web_sm
nlp = en_core_web_sm.load()
doc = nlp("This is a sentence.")
print([(w.text, w.pos_) for w in doc])

1. What kind of posts have the highest read ratio? 
2. What kind of post people recommend but no one finishes? 
3.